### ISSUE TITLE
import pyorc issue

### ISSUE THREAD

**Issue by lflowers39** [localdevices/pyorc#163]
OS: Windows 10 Enterprise (OS Build = 19045.4291). 
python version 3.12.3
Installed from pypi with pip

conda activate <name-of-your-environment>
conda install -c conda-forge cartopy geopandas rasterio
pip install pyopenrivercam

Full Error:
>>> import pyorc
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
Traceback (most recent call last):
  File "rasterio\\crs.pyx", line 586, in rasterio.crs.CRS.from_epsg
  File "rasterio\\_err.pyx", line 195, in rasterio._err.exc_wrap_int
rasterio._err.CPLE_AppDefinedError: PROJ: proj_create_from_database: Cannot find proj.db

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lflores\Anaconda3\envs\EAsPyORC\Lib\site-packages\pyorc\__init__.py", line 2, in <module>
    from .api.cameraconfig import CameraConfig, load_camera_config, get_camera_config
  File "C:\Users\lflores\Anaconda3\envs\EAsPyORC\Lib\site-packages\pyorc\api\cameraconfig.py", line 17, in <module>
    from .. import cv, helpers
  File "C:\Users\lflores\Anaconda3\envs\EAsPyORC\Lib\site-packages\pyorc\cv.py", line 6, in <module>
    from pyorc import helpers
  File "C:\Users\lflores\Anaconda3\envs\EAsPyORC\Lib\site-packages\pyorc\helpers.py", line 227, in <module>
    def get_lons_lats(xs, ys, src_crs, dst_crs=CRS.from_epsg(4326)):
                                               ^^^^^^^^^^^^^^^^^^^
  File "rasterio\\crs.pyx", line 590, in rasterio.crs.CRS.from_epsg
rasterio.errors.CRSError: The EPSG code is unknown. PROJ: proj_create_from_database: Cannot find proj.db

**Comment by hcwinsemius** [comment]
Thanks for posting. It may take a bit of time due to holiday season but we'll look into it. It may be that the problem is with the python 3.12 version which a few months back still had some compatibility issues. 3.11 is likely to work. We'll check it out.

**Comment by hcwinsemius** [comment]
I found that this issue was closed. Did you manage to solve it? What was the solution? I may be able to improve code or documentation.

**Comment by lflowers39** [comment]
I reinstalled from conda-forge as opposed to using pypi.
