### ISSUE TITLE
AttributeError: partially initialized module 'pyorc' has no attribute 'Video' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Ilhamrafi** [localdevices/pyorc#190]
This example would return an error

**pyorc .py**

```
import pyorc
import matplotlib.pyplot as plt

video_file = "D:/data/sungai/Sungai/flow_gnputri.mp4"
video = pyorc.Video(video_file, start_frame=0, end_frame=1) 
frame = video.get_frame(0, method="rgb")

f = plt.figure(figsize=(10, 6))
plt.imshow(frame)
```
```
PS D:\LSPIV Project> & C:/Users/miniconda3/envs/pyorc-dev/python.exe "d:/LSPIV Project/LSPIV/river_flow_analysis_final/streamlit/pyorc.py"
Traceback (most recent call last):
  File "d:\LSPIV Project\LSPIV\river_flow_analysis_final\streamlit\pyorc.py", line 1, in <module>
    import pyorc
  File "d:\LSPIV Project\LSPIV\river_flow_analysis_final\streamlit\pyorc.py", line 8, in <module>
    video = pyorc.Video(video_file, start_frame=0, end_frame=1)
            ^^^^^^^^^^^
AttributeError: partially initialized module 'pyorc' has no attribute 'Video' (most likely due to a circular import)
```

**Comment by Ilhamrafi** [comment]
I don't think I missed anything when installing pyopenrivercam, so can you help me?

**Comment by hcwinsemius** [comment]
Can you provide...

* Method by which you installed (pip or conda)
* Version installed. You can check this with

` ` ` python
import pyorc
pyorc.__version__
` ` `

**Comment by Ilhamrafi** [comment]
1. I'm using conda method to install Pyorc
2. I'm installing the new version '0.6.1'

I don't know why the error occurs, but when I use Jupyter Notebook the code runs smoothly, Meanwhile when I use the .py format it gets an error.

**Comment by hcwinsemius** [comment]
I will try to replicate this. In the meantime, are you confident that you activate the right environment whilst running from a ` .py``  file?

**Comment by hcwinsemius** [comment]
I have tried reproducing as follows:

```bash
mamba create --name pyorc_bug
mamba activate pyorc_bug
mamba install pyopenrivercam=0.6.1

python bug.py  # bug.py contains your code, with video replaced by one of my own.
```
I don't have any issue running like this.

Can you perhaps try the following:
```bash
mamba activate <name-of-your-env>
mamba install pyopenrivercam --force-reinstall  # forces to reinstall, if package is broken by some process, this may fix it
python <your-script.py>
```

**Comment by Ilhamrafi** [comment]
OK, thank you, my coding is working well now!
